namespace Qydha.Domain.Constants;
public static class BalootConstants
{
    public static readonly Dictionary<SunMoshtaraScoresId, MoshtaraScore> SunRoundScores = new(){
        {SunMoshtaraScoresId.khosaretKaboot , new(){DisplayValue = "خسارة كبوت" , Name="khosaretKaboot" , Value = 0}},
        {SunMoshtaraScoresId.khosara , new(){DisplayValue = "خسارة" , Name="khosara" , Value = 0}},
        {SunMoshtaraScoresId.Num_0 , new(){DisplayValue = "0" , Name="Num_0" , Value = 0}},
        {SunMoshtaraScoresId.Num_1 , new(){DisplayValue = "1" , Name="Num_1" , Value = 1}},
        {SunMoshtaraScoresId.Num_2 , new(){DisplayValue = "2" , Name="Num_2" , Value = 2}},
        {SunMoshtaraScoresId.Num_3 , new(){DisplayValue = "3" , Name="Num_3" , Value = 3}},
        {SunMoshtaraScoresId.Num_4 , new(){DisplayValue = "4" , Name="Num_4" , Value = 4}},
        {SunMoshtaraScoresId.Num_5 , new(){DisplayValue = "5" , Name="Num_5" , Value = 5}},
        {SunMoshtaraScoresId.Num_6 , new(){DisplayValue = "6" , Name="Num_6" , Value = 6}},
        {SunMoshtaraScoresId.Num_7 , new(){DisplayValue = "7" , Name="Num_7" , Value = 7}},
        {SunMoshtaraScoresId.Num_8 , new(){DisplayValue = "8" , Name="Num_8" , Value = 8}},
        {SunMoshtaraScoresId.Num_9 , new(){DisplayValue = "9" , Name="Num_9" , Value = 9}},
        {SunMoshtaraScoresId.Num_10 , new(){DisplayValue = "10" , Name="Num_10" , Value = 10}},
        {SunMoshtaraScoresId.Num_11 , new(){DisplayValue = "11" , Name="Num_11" , Value = 11}},
        {SunMoshtaraScoresId.Num_12 , new(){DisplayValue = "12" , Name="Num_12" , Value = 12}},
        {SunMoshtaraScoresId.Num_13 , new(){DisplayValue = "13" , Name="Num_13" , Value = 13}},
        {SunMoshtaraScoresId.Num_14 , new(){DisplayValue = "14" , Name="Num_14" , Value = 14}},
        {SunMoshtaraScoresId.Num_15 , new(){DisplayValue = "15" , Name="Num_15" , Value = 15}},
        {SunMoshtaraScoresId.Num_16 , new(){DisplayValue = "16" , Name="Num_16" , Value = 16}},
        {SunMoshtaraScoresId.Num_17 , new(){DisplayValue = "17" , Name="Num_17" , Value = 17}},
        {SunMoshtaraScoresId.Num_18 , new(){DisplayValue = "18" , Name="Num_18" , Value = 18}},
        {SunMoshtaraScoresId.Num_19 , new(){DisplayValue = "19" , Name="Num_19" , Value = 19}},
        {SunMoshtaraScoresId.Num_20 , new(){DisplayValue = "20" , Name="Num_20" , Value = 20}},
        {SunMoshtaraScoresId.Num_21 , new(){DisplayValue = "21" , Name="Num_21" , Value = 21}},
        {SunMoshtaraScoresId.Num_22 , new(){DisplayValue = "22" , Name="Num_22" , Value = 22}},
        {SunMoshtaraScoresId.Num_23 , new(){DisplayValue = "23" , Name="Num_23" , Value = 23}},
        {SunMoshtaraScoresId.Num_24 , new(){DisplayValue = "24" , Name="Num_24" , Value = 24}},
        {SunMoshtaraScoresId.Num_25 , new(){DisplayValue = "25" , Name="Num_25" , Value = 25}},
        {SunMoshtaraScoresId.Num_26 , new(){DisplayValue = "26" , Name="Num_26" , Value = 26}},
        {SunMoshtaraScoresId.Kaboot , new(){DisplayValue = "كبوت" , Name="Kaboot" , Value = 44}},
        {SunMoshtaraScoresId.DoubleSun , new(){DisplayValue = "دبل صن" , Name="DoubleSun" , Value = 52}},
    };
    public static readonly Dictionary<HokmMoshtaraScoresId, MoshtaraScore> HokmRoundScores = new(){
        {HokmMoshtaraScoresId.khosaretKaboot , new(){DisplayValue = "خسارة كبوت" , Name="khosaretKaboot" , Value = 0}},
        {HokmMoshtaraScoresId.khosara , new(){DisplayValue = "خسارة" , Name="khosara" , Value = 0}},
        {HokmMoshtaraScoresId.Num_0 , new(){DisplayValue = "0" , Name="Num_0" , Value = 0}},
        {HokmMoshtaraScoresId.Num_1 , new(){DisplayValue = "1" , Name="Num_1" , Value = 1}},
        {HokmMoshtaraScoresId.Num_2 , new(){DisplayValue = "2" , Name="Num_2" , Value = 2}},
        {HokmMoshtaraScoresId.Num_3 , new(){DisplayValue = "3" , Name="Num_3" , Value = 3}},
        {HokmMoshtaraScoresId.Num_4 , new(){DisplayValue = "4" , Name="Num_4" , Value = 4}},
        {HokmMoshtaraScoresId.Num_5 , new(){DisplayValue = "5" , Name="Num_5" , Value = 5}},
        {HokmMoshtaraScoresId.Num_6 , new(){DisplayValue = "6" , Name="Num_6" , Value = 6}},
        {HokmMoshtaraScoresId.Num_7 , new(){DisplayValue = "7" , Name="Num_7" , Value = 7}},
        {HokmMoshtaraScoresId.Num_8 , new(){DisplayValue = "8" , Name="Num_8" , Value = 8}},
        {HokmMoshtaraScoresId.Num_9 , new(){DisplayValue = "9" , Name="Num_9" , Value = 9}},
        {HokmMoshtaraScoresId.Num_10 , new(){DisplayValue = "10" , Name="Num_10" , Value = 10}},
        {HokmMoshtaraScoresId.Num_11 , new(){DisplayValue = "11" , Name="Num_11" , Value = 11}},
        {HokmMoshtaraScoresId.Num_12 , new(){DisplayValue = "12" , Name="Num_12" , Value = 12}},
        {HokmMoshtaraScoresId.Num_13 , new(){DisplayValue = "13" , Name="Num_13" , Value = 13}},
        {HokmMoshtaraScoresId.Num_14 , new(){DisplayValue = "14" , Name="Num_14" , Value = 14}},
        {HokmMoshtaraScoresId.Num_15 , new(){DisplayValue = "15" , Name="Num_15" , Value = 15}},
        {HokmMoshtaraScoresId.Num_16 , new(){DisplayValue = "16" , Name="Num_16" , Value = 16}},
        {HokmMoshtaraScoresId.Kaboot , new(){DisplayValue = "كبوت" , Name="Kaboot" , Value = 25}},
        {HokmMoshtaraScoresId.Double , new(){DisplayValue = "دبل" , Name="Double" , Value = 32}},
        {HokmMoshtaraScoresId.Three , new(){DisplayValue = "ثرى" , Name="Three" , Value = 48}},
        {HokmMoshtaraScoresId.Four , new(){DisplayValue = "فور" , Name="Four" , Value = 64}},
        {HokmMoshtaraScoresId.Kahwa , new(){DisplayValue = "قهوة" , Name="Kahwa" , Value = 152}},
    };

    public static readonly int[] SakkaCountPerGameValues = [1, 3, 5, 7, 9, 11];
}
