CREATE TABLE Notification (
    Notification_Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY Key,
    Title VARCHAR(255) NOT NULL,
    Description VARCHAR(512) NOT NULL,
    Read_At TIMESTAMP ,
    Created_At TIMESTAMP NOT NULL,
    Action_Path VARCHAR(350),
    Action_Type SMALLINT NOT NULL ,
    User_Id uuid NOT NULL,
    CONSTRAINT fk_user_notification
        FOREIGN KEY(User_Id)
            REFERENCES Users(id)
            ON DELETE CASCADE
);